### ISSUE TITLE
Possibility to override default headers

### ISSUE THREAD

**Issue by rrva** [launchdarkly/okhttp-eventsource#38] opened 2019-10-03 06:02 UTC
If I want to override the Accept: text/event-stream HTTP header for some broken backends which need another value of Accept, it seems that the EventSource builder does not let me do that, since private static Headers addDefaultHeader is called overwriting any Accept value I try to set myself in the builder. Please add a mechanism to either disable any default headers being set, or to alter the accept header specifically

**Comment by eli-darkly** [comment] 2019-10-12 00:05
Sorry for the delay in responding to this. This should be a simple fix. To be clear, the problem is not exactly that `addDefaultHeader` is _overwriting_ your Accept header; if you look at how that method is implemented, it is putting the standard Accept header in first, and _then_ applying the headers you specified. The problem is that `Headers.Builder.add()` does _not_ overwrite existing values; it adds to them, so you are ending up with two values for the `Accept` header. That is theoretically OK, but your server might not be set up to handle it (like, maybe it is checking for an exact match to one specific value).

So, it should be easy enough for us to make it simply omit the default value for `Accept` or `Cache-Control` if you provided your own value(s).

**Comment by eli-darkly** [comment] 2019-10-18 01:33
Fixed in 1.10.1.

**Closed by eli-darkly** 2019-10-18 01:33 UTC
